apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crushftp.fullname" . }}
  labels:
    {{- include "crushftp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "crushftp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "crushftp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "crushftp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CRUSH_ADMIN_USER
              value: {{ .Values.admin.username | quote }}
            - name: CRUSH_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "crushftp.fullname" . }}-secret 
                  key: {{ .Values.secrets.appsecret }}
            - name: CRUSH_ADMIN_PROTOCOL
              value: {{ .Values.admin.protocol | quote }}
            - name: CRUSH_ADMIN_PORT
              value: {{ .Values.admin.port | quote }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
            - name: sftp
              containerPort: 2222
              protocol: TCP
            {{- if .Values.features.enableFtp }}
            - name: ftp
              containerPort: 21
              protocol: TCP
              {{- range (untilStep 0 101 1) }}
            - name: 'ftp-pas-{{ . }}'
              containerPort: {{ add 2000 . }}
              protocol: TCP
              {{- end }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: / 
              port: 443
              scheme: HTTPS
            timeoutSeconds: 10
            initialDelaySeconds: 240
            failureThreshold: 3
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: / 
              port: 443
              scheme: HTTPS
            failureThreshold: 24
            initialDelaySeconds: 240
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: / 
              port: 443
              scheme: HTTPS
            timeoutSeconds: 10
            initialDelaySeconds: 240
            failureThreshold: 3
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range .Values.volumes }}
            - name: {{ .name }}-volume
              mountPath: {{ .mountPath }}
            {{- end }}
            - name: secret-kv-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secret-kv-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kvname-system-msi

        {{- range .Values.volumes }}
        - name: {{ .name }}-volume
          csi:
            driver: file.csi.azure.com
            volumeAttributes:
               server: {{ .server }}
               shareName: {{ .shareName }}
               secretName: crushftp-sa-secret
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

