# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  secretObjects:
  - secretName: {{ include "crushftp.fullname" . }}-secret
    type: Opaque
    data:
    - objectName: {{ .Values.secrets.appsecret }}
      key: {{ .Values.secrets.appsecret }}
  - secretName: {{ include "crushftp.fullname" . }}-sa-secret
    type: Opaque
    data:
    - objectName: {{ .Values.storageaccountname }}
      key: {{ .Values.storageaccountname }}
    - objectName: {{ .Values.storageaccountkey }}
      key: {{ .Values.storageaccountkey }}
  - secretName: {{ include "crushftp.fullname" .  }}-tls
    type: tls
    data:
    - objectName: {{ .Values.certs.appcert }} 
      key: tls.crt 
    - objectName: {{ .Values.keys.appkey }} 
      key: tls.key 
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: {{ .Values.keyvault.identity }}      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: {{ .Values.keyvault.name }} 
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: {{ .Values.certs.appcert }}
          objectType: cert        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: {{ .Values.secrets.appsecret }}
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: {{ .Values.storageaccountname }}
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: {{ .Values.storageaccountkey }}
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty

        - |
          objectName: {{ .Values.keys.appkey }}
          objectType: key
          objectVersion: ""     
    tenantId: {{ .Values.tenantid }}           # The tenant ID of the key vault

