apiVersion: v1
kind: Service
metadata:
  name: {{ include "crushftp.fullname" . }}
  labels:
    {{- include "crushftp.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: sftp
      port: 2222
      targetPort: 2222
      protocol: TCP
    {{- if .Values.features.enableFtp }}
    - name: ftp
      port: 21
      targetPort: 21
      protocol: TCP
      {{- range (untilStep 0 101 1) }}
    - name: 'ftp-pas-{{ . }}'
      port: {{ add 2000 . }}
      targetPort: {{ add 2000 . }}
      protocol: TCP
      {{- end }}
    {{- end }}
  selector:
  
    {{- include "crushftp.selectorLabels" . | nindent 4 }}
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.loadBalancerIp }}
